- id: back_door_night
  alias: Back door (night)
  trigger:
    platform: state
    entity_id: sensor.deck_door
    from: Closed
    to: Open
  condition:
    condition: time
    after: '21:00'
  action:
    service: notify.ios_gm_iphone
    data:
      message: Deck door open
      data:
        push:
          badge: 5
- id: basement_door_night
  alias: Basement door (night)
  trigger:
    platform: state
    entity_id: sensor.basement_door
    from: Closed
    to: Open
  condition:
    condition: time
    after: '21:00'
  action:
    service: notify.ios_gm_iphone
    data:
      message: Basement door open
      data:
        push:
          badge: 1
- id: front_door_night
  alias: Front door (night)
  trigger:
    platform: state
    entity_id: sensor.front_door
    from: Closed
    to: Open
  condition:
    condition: time
    after: '21:00'
  action:
    service: notify.ios_gm_iphone
    data:
      message: Front door open
      data:
        push:
          badge: 10
- id: night_theme
  alias: Set dark theme for the night
  initial_state: true
  trigger:
    platform: time
    at: '19:00'
  action:
  - service: frontend.set_theme
    data:
      name: darkcyan
- id: turn_office_light_on_night_motion
  alias: Office light on when motion at night
  trigger:
  - entity_id: sensor.office_motion
    platform: state
    to: detected
  - event: sunset
    offset: -00:45:00
    platform: sun
  condition:
  - after: '14:00:00'
    before: '23:00:00'
    condition: time
  action:
  - entity_id: light.office_light_level
    service: light.turn_on
- id: turn_office_light_off_after_5_min
  alias: Office light off after 5 min when motion off
  trigger:
  - entity_id: sensor.office_motion
    for:
      minutes: 5
      seconds: 0
    platform: state
    to: clear
  action:
  - entity_id: light.office_light_level
    service: light.turn_off
- id: rain_snow_day_lights
  alias: Rain/Snow Day
  trigger:
  - platform: state
    entity_id: sensor.dark_sky_precip
    to: rain
  - platform: state
    entity_id: sensor.dark_sky_precip
    to: snow
  condition:
  - condition: state
    entity_id: group.family
    state: home
  - condition: time
    after: '8:00'
    before: '23:00'
  action:
    service: light.turn_on
    entity_id: light.office_light_level
- id: rain_snow_day_over
  alias: Rain/Snow is over
  trigger:
    platform: state
    entity_id: sensor.dark_sky_precip_intensity
    to: None
  condition:
    condition: sun
    after: sunset
    after_offset: -01:00:00
  action:
    service: light.turn_off
    entity_id: light.office_light_level
- id: alarm_armed_away
  alias: '[Alarm] Away Mode Armed'
  trigger:
    platform: state
    entity_id: alarm_control_panel.house
    to: armed_away
  action:
    data:
      message: Alarm Away Mode Armed
      target: email/gregory.mills@gmail.com
    service: notify.pushbullet
- id: alarm_armed_home
  alias: '[Alarm] Home Mode Armed'
  trigger:
    platform: state
    entity_id: alarm_control_panel.house
    to: armed_home
  action:
    data:
      message: Alarm Home Mode Armed
      target: email/gregory.mills@gmail.com
    service: notify.pushbullet
- id: alarm_arming_away
  alias: '[Alarm] Away Mode Arming'
  trigger:
    platform: state
    entity_id: alarm_control_panel.house
    to: pending
  action:
- id: alarm_disarmed
  alias: '[Alarm] Disarmed'
  trigger:
    platform: state
    entity_id: alarm_control_panel.house
    to: disarmed
  action:
    service: notify.pushbullet
    data:
      message: Alarm Disabled
      target: email/gregory.mills@gmail.com
- id: alarm_triggered
  alias: '[Alarm] Triggered'
  trigger:
    platform: state
    entity_id: alarm_control_panel.house
    to: triggered
  action:
    service: notify.pushbullet
    data:
      message: ALARM TRIGGERED!!! {{ states[states.alarm_control_panel.house.attributes.changed_by.split(".")[0]][
        states.alarm_control_panel.house.attributes.changed_by.split(".")[1]].name
        }}
      target: email/gregory.mills@gmail.com
- id: alarm_warning
  alias: '[Alarm] Warning'
  trigger:
    platform: state
    entity_id: alarm_control_panel.house
    to: warning
  action:
    service: notify.pushbullet
    data:
      message: ALARM Warning {{ states[states.alarm_control_panel.house.attributes.changed_by.split(".")[0]][
        states.alarm_control_panel.house.attributes.changed_by.split(".")[1]].name
        }}
      target: email/gregory.mills@gmail.com
- id: alarm_auto_home_disarm
  alias: '[Alarm] Auto Home Disarm'
  trigger:
    platform: state
    entity_id: device_tracker.greg, device_tracker.katie
    from: not_home
    to: home
  condition:
    condition: state
    entity_id: alarm_control_panel.house
    state: armed_away
  action:
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.house
    data:
      code: 4831
  - service: notify.pushbullet
    data:
      message: ALARM Auto Disarmed
      target: email/gregory.mills@gmail.com
- id: alarm_auto_away_arm
  alias: '[Alarm] Auto Away Arm'
  trigger:
    platform: state
    entity_id: device_tracker.greg, device_tracker.katie
    from: home
    to: not_home
  condition:
    condition: state
    entity_id: alarm_control_panel.house
    state: disarmed
  action:
  - service: alarm_control_panel.alarm_arm
    entity_id: alarm_control_panel.house
  - service: notify.pushbullet
    data:
      message: ALARM Auto Armed
      target: email/gregory.mills@gmail.com
- id: alarm_night_auto_home_arm
  alias: '[Alarm] Auto Night Home Arm'
  trigger:
    platform: time
    at: '22:00:00'
  condition:
    condition: state
    entity_id: alarm_control_panel.house
    state: disarmed
  action:
    service: alarm_control_panel.armed_home
    entity_id: alarm_control_panel.house
